language: ruby
rvm:
  - 2.1.2
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database give_me_something_test;' -U postgres
  - bundle exec rake db:migrate --trace
